services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: ./Dockerfile

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always